global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    test_type: "${TYPE_TEST}"

scrape_configs:
  - job_name: "api-python"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["api:8000"]
        labels:
          service: "api"

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
        labels:
          service: "database"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
